
all:
	make -C omxcore/
	make -C vdec/
	make -C venc/

clean:
	make clean -C omxcore/
	make clean -C vdec/
	make clean -C venc/

cleanall:
	make cleanall -C omxcore/
	make cleanall -C vdec/
	make cleanall -C venc/

.PHONY: all clean cleanall

